name: ChemSpaceGen
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - hdbscan=0.8.26
  - matplotlib-base=3.3.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.3
  - python=3.6.10
  - rdkit=2020.09.3
  - scikit-learn=0.22.1
  - scipy=1.5.4
